### ISSUE TITLE
Feature Request: aazDev to support YAML for the short-hand syntax support

### ISSUE THREAD

**Issue by panchagnula** [Azure/aaz-dev-tools#109]
The short hand syntax with ?? is a great feature. https://github.com/Azure/azure-cli/blob/dev/doc/shorthand_syntax.md

For app Service & Azure container apps alike we gathered feedback that YAML instead of JSON is considered as the format for developers. It is for the same reason we offer --yaml as an option for advanced users with our create & update commands.
Hence, can YAML also be supported, with JSON as default?

**Comment by panchagnula** [comment]
@kairu-ms any update on this? We did evaluation on our end to use CodeGenV2 & this is the only blocker on our end to move to core-cli, since --yaml is a parameter used actively by advanced users. Thanks! https://docs.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-create

**Comment by kairu-ms** [comment]
Hi @panchagnula, I'm working on it. We will support yaml file as an input value while using shorthand syntax. But I'm afraid we will not provide an additional argument called `--yaml`. Is that ok?
