### ISSUE TITLE
Required properties with no required sub-properties omits empty object in ReST PUT call

### ISSUE THREAD

**Issue by bryan-strassner** [Azure/aaz-dev-tools#383]
When attempting to generate a CLI from OpenAPI/swagger with the following:
```
    "KubernetesClusterFeature": {
      "type": "object",
      "title": "KubernetesClusterFeature represents the feature of a Kubernetes cluster.",
      "required": [
        "properties"
      ],
      "properties": {
        "properties": {
          "$ref": "#/definitions/KubernetesClusterFeatureProperties",
          ... 
```
where the `properties` property has no required fields within.

When any of the subordinate fields are specified, the correct body is produced.
However, when none of the child fields of the `properties` field are specified in the CLI command, the entire required property is omitted.

Expected:
```
PUT .../kubernetesClusterFeatures/someFeature

{
    "properties": {}
}
```

Instead produced:
```
PUT .../kubernetesClusterFeatures/someFeature

{}
```

This is a malformed request.

Reference this swagger: https://github.com/Azure/azure-rest-api-specs-pr/blob/62cbc2823818c586464a030bd1e80a39df9da4f8/specification/networkcloud/resource-manager/Microsoft.NetworkCloud/preview/2024-06-01-preview/networkcloud.json#L9791

**Comment by kairu-ms** [comment]
I tried the generated code, it works correctly. Did you using the latest version of aaz-dev-tools?
![image](https://github.com/user-attachments/assets/ae372b32-fef2-409c-bb43-a03fe1e7a044)

**Comment by bryan-strassner** [comment]
Closing this - there is no issue with the generation from the CLI perspective. The reported issue is coming from a different layer in the service framework.
